on:
    push:
      branches:
        - main
        - master


name: "Build & Release"

jobs:
    build:
        name: Build & Release
        runs-on: windows-latest
        steps:
          - name: Checkout ğŸ›ï¸
            uses: actions/checkout@v3

          - name: Java Setup ğŸ”
            uses: actions/setup-java@v3
            with:
              java-version: '11'
              distribution: 'temurin'

          - name: Flutter Setup
            uses: subosito/flutter-action@v2
            with:
                channel: stable
                flutter-version: '3.24.4'

          - name: Dependencies install
            run: flutter pub get

          - name: Integration Test ğŸ§ª
            run: flutter test -d windows integration_test\app_test.dart

          - name: Building exe for Windows âš¡
            run: flutter build windows --release --build-name 1.1.${{ github.run_number }} --build-number ${{ github.run_number }}

          - name: Archive Release
            uses: thedoctor0/zip-release@master
            with:
                type: 'zip'
                filename: Sangeet-v1.1.${{ github.run_number }}_windows_x64.zip
                directory: build/windows/x64/runner/Release

          - name: Push to Releases
            uses: ncipollo/release-action@v1
            with:
                artifacts: "build/windows/x64/runner/Release/Sangeet-v1.1.${{ github.run_number }}_windows_x64.zip"
                tag: v1.1.${{ github.run_number }}
                token: ${{ secrets.GITHUB_TOKEN }}
                draft: true
                generateReleaseNotes: true