on:
    pull_request:
        branches:
          - main
          - master
          - dev
    push:
      branches:
        - main
        - master
        - dev


name: "Integration Tests"

jobs:
    run_tests:
        name: Run Integration Tests
        runs-on: windows-latest
        steps:
          - name: Checkout ğŸ›ï¸
            uses: actions/checkout@v3

          - name: Java Setup ğŸ”
            uses: actions/setup-java@v3
            with:
              java-version: '11'
              distribution: 'temurin'

          - name: Flutter setup ğŸ”
            uses: subosito/flutter-action@v2
            with:
                channel: stable
                flutter-version: '3.24.4'

          - name: Dependencies install
            run: flutter pub get

          - name: Integration Test ğŸ§ª
            run: flutter test -d windows integration_test\app_test.dart


